### PR TITLE
ncm-accounts: fix some useful accounts on CentOS 7.2

### PR DESCRIPTION
**Pull request by guillaume-philippon**
Fix issue #681.

### CODE REVIEW

**Comment by jouvin** [comment]
For an easier maintenance of this file in the future, I'd suggest to sort the list of kept users/groups....

**Comment by jouvin** [comment]
BTW, the list is not complete, see https://github.com/quattor/template-library-os/pull/74.

**Comment by jouvin** [comment]
Note that if you installed a CentOS 7 box without this or the relevant fix for `ncm-accounts`, you may need to recreate all users/groups that may have been removed by `ncm-accounts` and created by those 2 RPMS (`rpm -q xxx --scripts` to see them). You may be affected by the problem if you run `ncm-accounts` with `remove_unknown=true` (recommended). Whether you are impacted or not depends on the setting of `preserved_accounts` and the actual value of `SYS_UID_MIN/MAX`  and `UID_MIN/MAX`.

**Comment by jrha** [comment]
@guillaume-philippon, the correct syntax is "Fixes #681"

**Pull request merged**
