### PR TITLE
ncm-metaconfig: ganesha: Access_Type should be enum, not string

### PR DESCRIPTION
**Pull request by kwaegema**
This is mainly for gpfs CES that does not like this

### CODE REVIEW

**Comment by stdweird** [comment]
jenkins test this please

**Comment by stdweird** [comment]
jenkins test this please

**Comment by stdweird** [comment]
jenkins test this please

**Comment by jrha** [comment]
rebased

**Comment by jrha** [comment]
Looks like twelve regex tests are failing:
```
not ok 663 - Found at least one match (total 0 matches) for test idx 6 (pattern (?^:(?m:^\s{4}Access_Type = None;$)))
not ok 664 - Order ok for test idx 6 (pattern (?^:(?m:^\s{4}Access_Type = None;$))) (lastpos 57 before -1)
not ok 773 - Found at least one match (total 0 matches) for test idx 61 (pattern (?^:(?m:^\s{4}Filesystem_id = 666.666;$)))
not ok 774 - Order ok for test idx 61 (pattern (?^:(?m:^\s{4}Filesystem_id = 666.666;$))) (lastpos 1554 before -1)
not ok 1023 - Found at least one match (total 0 matches) for test idx 2 (pattern (?^:(?m:^\s{4}Filesystem_id = 192.168;$)))
not ok 1024 - Order ok for test idx 2 (pattern (?^:(?m:^\s{4}Filesystem_id = 192.168;$))) (lastpos 330 before -1)
not ok 1039 - Found at least one match (total 0 matches) for test idx 10 (pattern (?^:(?m:^\s{8}Access_Type = RW;$)))
not ok 1040 - Order ok for test idx 10 (pattern (?^:(?m:^\s{8}Access_Type = RW;$))) (lastpos 537 before -1)
not ok 1067 - Found at least one match (total 0 matches) for test idx 24 (pattern (?^:(?m:^\s{4}Filesystem_id = 192.168;$)))
not ok 1068 - Order ok for test idx 24 (pattern (?^:(?m:^\s{4}Filesystem_id = 192.168;$))) (lastpos 742 before -1)
not ok 1083 - Found at least one match (total 0 matches) for test idx 32 (pattern (?^:(?m:^\s{8}Access_Type = RW;$)))
not ok 1084 - Order ok for test idx 32 (pattern (?^:(?m:^\s{8}Access_Type = RW;$))) (lastpos 949 before -1)
```

**Comment by kwaegema** [comment]
@jrha fixed that

**Review by jrha — APPROVED** [review]

**Comment by jrha** [comment]
Does this break backwards compatibility or was it always broken?

**Pull request merged**
