### PR TITLE
ncm-metaconfig: logstash and elasticsearch 2.0 support

### PR DESCRIPTION
**Pull request by stdweird**

### CODE REVIEW

**Comment by jrha** [comment]
Is this backward compatible?

**Comment by jrha** [comment]
Can this not be made backwards compatible by having a major version in the name?

**Comment by stdweird** [comment]
@jrha we will probably create a very different `logstash2` later. the current schema is not adapted to the utter mess they made of their config format :unamused:

**Comment by jrha** [comment]
Typo in bcc8211 commit message (metaocnifg)

**Comment by stdweird** [comment]
@jrha typo fixed and rebased

**Pull request merged**
