### PR TITLE
ncm-icinga: file permissions changed to 0440 for config files instead…

### PR DESCRIPTION
**Pull request by wdpypere**
… of 0444.

Monitoring configuration tells you a lot about an environment and can contain sensitive information, therefore should not be world readable.

### CODE REVIEW

**Comment by jrha** [comment]
Well that broke it...

**Comment by wdpypere** [comment]
because I now close the filehandles in the function, the test fail. I'll see if I can fix it.

**Comment by wdpypere** [comment]
@jrha tests are fixed.

**Comment by jrha** [comment]
:green_heart:

**Pull request merged**
