### PR TITLE
ncm-metaconfig: httpd support GSSAPI auth

### PR DESCRIPTION
**Pull request by stdweird**
Add support for GSSAPI auth and example/unittests of apache config for retrieving profiles using kerberos

### CODE REVIEW

**Comment by jrha** [comment]
Looks reasonable, but I have no experience with Apache and GSSAPI.

**Comment by jrha** [comment]
@stdweird where did all the ncm-nfs commits come from?

**Comment by stdweird** [comment]
@jrha rebased

**Comment by jrha** [comment]
Thanks!

**Pull request merged**
