### PR TITLE
ncm-gpfs: add gpfs.hadoop-connector to gpfs packages

### PR DESCRIPTION
**Pull request by kwaegema**
add gpfs.hadoop-connector to gpfs packages

### CODE REVIEW

**Comment by stdweird** [comment]
LGTM

**Comment by stdweird** [comment]
@kwaegema change title pls

**Comment by jrha** [comment]
@kwaegema, can you rebase this to get rid of the merge commits? Otherwise it is good to go.

**Comment by kwaegema** [comment]
@jrha done

**Pull request merged**
