### PR TITLE
ncm-pam: new function pam_add_access_group

### PR DESCRIPTION
**Pull request by ned21**
New function which mirrors the ability to add netgroups to the components/pam/access with one that can handle unix groups.

Also some small clean ups to remove un-necessary returns().

### CODE REVIEW

**Comment by ned21** [comment]
I think those lint errors are fixable (also just spotted a typo)

**Comment by ned21** [comment]
Sadly the panlint errors are not trivially fixable without code changes that would require more significant testing.

**Comment by jrha** [comment]
@stdweird?

**Comment by stdweird** [comment]
@ned21 current panlint errors are very easy to fix. it's misisng 1 include to fix 11 errors and 1 whitespace issue.

**Comment by ned21** [comment]
@stdweird - I tried adding the standard boilerplate header and it only reduced it to [10](https://travis-ci.org/quattor/configuration-modules-core/builds/279611865) errors which didn't seem worth the improvement. Looking again it might have been that the patch I tried introduced new errors which I mis-read as "not having fixed the old ones" but might have just been the way emacs formatted my continuation lines.

I'll have another look to see if we can clean this up in a separate PR.

**Comment by ned21** [comment]
@stdweird OK now I remember why I thought this was as good as we could get. The include issues can't be fixed because it's complaining that this file should include itself. The first 5 could be fixed with a prefix command but the if() statements won't be. I think the only way to fix this is to move the functions to a new functions file and hope panlint doesn't expect to see an include components/config in there too. 

The whitespace error I disagree with: 
```pam_add_access_acl(key, "+", "("+group+")", "ALL");```

is more readable than:

```pam_add_access_acl(key, "+", "(" + group + ")", "ALL");```

**Pull request merged**
