### PR TITLE
ncm-spma: yum create and use cache

### LINKED ISSUE #689: ncm-spma: bug in cleanup of repos
it seems there is no cleanup between failed yum transaction and second attempt.

This way, some repos can be enabled that shouldn't be there in that stage

### PR DESCRIPTION
**Pull request by stdweird**
Fixes #689 
Based on #710

### CODE REVIEW

**Comment by stdweird** [comment]
@jrha feel free to move the milestone to 16.4

**Comment by stdweird** [comment]
this is not ready for 16.2

**Comment by jrha** [comment]
Is it ready for 16.4?

**Comment by stdweird** [comment]
we are running this everywhere

**Pull request merged**
