### PR TITLE
ncm-fstab, ncm-filesystems: pass logger to NCM::Blockdevices

### PR DESCRIPTION
**Pull request by kwaegema**
Depends on https://github.com/quattor/ncm-lib-blockdevices/pull/70

### CODE REVIEW

**Comment by stdweird** [comment]
LGTM

**Comment by jrha** [comment]
LGTM also

**Comment by ned21** [comment]
The code looks fine but there are other changes here which are not described in the commit log. Is the removal of those stub files intentional or an accidental inclusion? Should their removal be done as part of a separate commit?

**Comment by kwaegema** [comment]
@ned21 made seperate commit for removing the stubs

**Pull request merged**
