### PR TITLE
Add metaconfig usage tutorial

### PR DESCRIPTION
**Pull request by stdweird**
This is the second half of the textrender/metaconfig tutorial given during the 19th workshop

### CODE REVIEW

**Comment by jrha** [comment]
Would this be better/worse on the website?

**Comment by wdpypere** [comment]
I think it would fit right in documentation/other with the other articles, maybe even with a reference on the blog.

**Comment by jrha** [comment]
@stdweird how do you feel about having this on the website instead? It would be good to give it maximum exposure.

**Comment by stdweird** [comment]
@jrha i have no real preference, just say where it should land. will have to review it if the CCM::TextRender PRs get merged.

**Comment by jrha** [comment]
@stdweird please open a new PR to add this as documentation on the website, I think it would fit best there.

**Pull request closed without merging**
