### PR TITLE
ncm-metaconfig example service

### PR DESCRIPTION
**Pull request by stdweird**
This adds the ncm-metaconfig example service

### CODE REVIEW

**Comment by stdweird** [comment]
Do not merge this. It is an example for a tutorial.

**Comment by stdweird** [comment]
@jrha can we have a branch to hold this? (if not, with a closed PR, if i ever delete my branch, this is all gone)

**Comment by jrha** [comment]
I've made a branch called examples so this can live somewhere.

**Comment by stdweird** [comment]
See #437

**Pull request closed without merging**
