### PR TITLE
network: nmstate add support for ovsintport and ovsbridge

### LINKED ISSUE #1718: ncm-network: nmstate, add support for OVS bridges and ports
OVS bridges and ports are not supported with ncm-network nmstate yet, just to add this example:

```
interfaces:
- name: eth100
  type: ovs-interface
  state: up
  ipv4:
    enabled: true
    address:
      - ip: 192.168.1.1
        prefix-length: 24
- name: br100
  type: ovs-bridge
  state: up
  bridge:
    options:
      stp: true
    port:
    - name: bond0
    - name: eth100
```
Including the new interface names for NetworkManager `ovs-bridge`and `ovs-interface`

### PR DESCRIPTION
**Pull request by stdweird**
Fixes #1718

### CODE REVIEW

**Review by jrha — DISMISSED** [review]

**Comment by stdweird** [comment]
@jrha this needs more tests, and probably a new device ordering method

**Comment by aka7** [comment]
@stdweird did you want to write all config in one file for nmstate and apply all in one go? I'm happy with that.

**Comment by stdweird** [comment]
@aka7 we are still figuring this one out. the ovs bridge code is very tricky it seems

**Review by jrha — APPROVED** [review]
This looks good to me now, assuming nothing else is missing @stdweird?

**Pull request merged**
