### PR TITLE
Fixes for EL5 and EL6

### PR DESCRIPTION
**Pull request by stdweird**

### CODE REVIEW

**Comment by stdweird** [comment]
EL5 tests were run with latest maven-tools (incl https://github.com/quattor/maven-tools/pull/42). EL6 work with latest 1.40 and with latest maven-tools (incl https://github.com/quattor/maven-tools/pull/42)

EL6 passes completely. 
EL5 tests now fail on ncm-named with some bizarre error.

**Comment by stdweird** [comment]
also on EL5 authconfig fails on the sssd TT rendering (for no obvious reason).

**Comment by stdweird** [comment]
3 components still fail on EL5:
 * ncm-authconfig fails 3 tests with same error 
{{{
#   Failed test 'No errors in rendering the template'
#   at src/test/perl/sssd.t line 51.
#          got: undef
#     expected: ''
}}}
  - seems harmless but odd, needs to be investigated
   - proposal: move the code to TextRender and test it properly #440

 * there are 2 components that require perl 5.10.1 (ie not on EL5)
  * ncm-ceph
  * ncm-icinga
  * howto deal with those: #441

**Comment by stdweird** [comment]
@jrha all other repos pass on EL5.

**Comment by jrha** [comment]
Awesome work thanks.

**Pull request merged**
