### PR TITLE
ncm-nfs: add cephfs share type to NFS component schema

### PR DESCRIPTION
**Pull request by Tom-Byrne**
Adding the ability to add CephFS network shares into fstab using ncm-nfs.

### CODE REVIEW

**Comment by jrha** [comment]
test this please

**Comment by stdweird** [comment]
@Tom-Byrne this needs changes in the compoennt code as well, grep fro panfs and add cephfs 
@kwaegema @alvarosimon do you remember the issues we had with cephfs in fstab? is that working now (in recent enough el6/el7)

**Comment by stdweird** [comment]
@kwaegema @alvarosimon or was that with ceph-fuse

**Comment by Tom-Byrne** [comment]
@stdweird Ah, didn't think about that, done in b53ca1a (unless I've missed anything else).

**Comment by stdweird** [comment]
@Tom-Byrne if you feel up to it, extend unittest
* add cephfs entry in https://github.com/quattor/configuration-modules-core/blob/master/ncm-nfs/src/test/resources/fstab_simple.pan
* hashref for cephfs simialr to https://github.com/quattor/configuration-modules-core/blob/master/ncm-nfs/src/test/perl/fstab.t#L142
* add regexp fro generated entry https://github.com/quattor/configuration-modules-core/blob/master/ncm-nfs/src/test/resources/regexps/fstab

**Comment by stdweird** [comment]
ok to test

**Comment by Tom-Byrne** [comment]
Finally got back around to extending the unit tests, should be all good to merge!

**Comment by stdweird** [comment]
@Tom-Byrne thx a lot

**Pull request merged**
