### PR TITLE
ncm-ceph: add -L to file

### PR DESCRIPTION
**Pull request by kwaegema**
let file follow symlinks to check if empty

### CODE REVIEW

**Comment by stdweird** [comment]
LGTM

**Comment by stdweird** [comment]
@kwaegema update branch

**Comment by stdweird** [comment]
@kwaegema  please ignore my remark on pressing the update branch button, in fact do never press that evil shiny green button, rebase instead

**Comment by kwaegema** [comment]
@stdweird done

**Comment by kwaegema** [comment]
@stdweird rebased again

**Pull request merged**
