### PR TITLE
ncm-metaconfig: add openvpn as replacement for ncm-openvpn

### PR DESCRIPTION
**Pull request by wdpypere**
I needed a fix for https://github.com/quattor/configuration-modules-core/issues/1104

As i'm no perl expert and saw that ncm-openvpn is on the "replace by metaconfig" list, here is the metaconfig openvpn config.

### CODE REVIEW

**Comment by wdpypere** [comment]
the schema is the schema of ncm-openvpn with some more strict checking and documentation.

**Comment by wdpypere** [comment]
tbh, I don't get why the tests are failing.

**Comment by jrha** [comment]
@hpcugentbot retest this please

**Comment by jrha** [comment]
@wdpypere you may need to rebase this now that the new build tools have been released

**Comment by wdpypere** [comment]
@jrha tests ran fine without rebase apparently.

**Comment by jrha** [comment]
Sweet

**Comment by stdweird** [comment]
@jrha reviewed 😄

**Pull request merged**
