### PR TITLE
bump build-scripts to 1.56

### PR DESCRIPTION
**Pull request by stdweird**

### CODE REVIEW

**Comment by jrha** [comment]
@hpcugentbot test this please

**Comment by jrha** [comment]
@stdweird thanks for sorting all of this out - any idea what's left to do with this one?

**Comment by stdweird** [comment]
i'm fighting with spma yum now, which does some pretty advanced things with filewriter. i might just comment out a single unittest to speed this up.

**Comment by jrha** [comment]
What could go wrong? :worried:

**Comment by stdweird** [comment]
@jrha 🍏 📗 💚 🥗

**Comment by jrha** [comment]
Awesome thanks!

**Pull request merged**
