### PR TITLE
ncm-systemd: ensure unit property is defined

### LINKED ISSUE #1787: ncm-systemd 24.10.0: validation fails if no unit is defined
In `ncm-systemd` since 21.12.0, a validation has been added to the schema for the main type `systemd_component` that accesses `unit` property in the structure. If the component has been loaded but no unit has been defined, this result in a validation error has the `unit` property is undefined.

### PR DESCRIPTION
**Pull request by jouvin**
Fixes #1787

### CODE REVIEW

**Comment by jrha** [comment]
Isn't the issue here that the schema marks it as optional, but the validation requires it to be present?

**Comment by jrha** [comment]
How about https://github.com/jrha/configuration-modules-core/commit/1abc38d4c7928385fa186398066f891724616dbf instead?

**Comment by jouvin** [comment]
@jrha I'm happy with your patch too, it should have the same effect for the use case I want to address. I think the main choice criteria between both approaches is whether the configuration module code can deal properly with an undefined `unit` property. Looking quickly at the code, I have the feeling that the code is not really prepared to deal with no units at all being defined but the actual unit list is built in `Systemd/Service.pm` by `gather_configured_units()` which merges systemd units and services defined in `ncm-chkconfig` so the risk of an empty unit list looks very small and will probably not match a meaningful usecase... So probably it doesn't make a big difference.

**Review by jrha — APPROVED** [review]

**Comment by jouvin** [comment]
@jrha please, could you merge this PR is you agree with as it would allow to fix errors in several other PRs currently open...

**Comment by jrha** [comment]
Sorry, was waiting for the tests to finish and got distracted!

**Pull request merged**
