### PR TITLE
ncm-metaconfig: rsyslog: Tighten up schema and use choice for options

### LINKED ISSUE #1193: ncm-metaconfig: rsyslog: Tighten up schema
Addressing minor comments from review of #1188.

### PR DESCRIPTION
**Pull request by jrha**
Resolves #1193.

### CODE REVIEW

**Comment by ned21** [comment]
PAN LGTM, anyone an rsyslog expert?

**Comment by jrha** [comment]
Someone at UGent perhaps? This could do with some tests that exercise these properties, if I get some time around the holidays I might try and add some.

**Comment by jrha** [comment]
I'm not going to find any time to add tests this year, it's already an improvement, so we could merge it now or bump it to next year.

**Comment by ned21** [comment]
Are we OK to merge stuff tagged 19.12?

**Comment by jrha** [comment]
Yep

**Pull request merged**
