### PR TITLE
ncm-systemd: allow non-listed unit(file)s that have valid show data

### LINKED ISSUE #677: ncm-chkconfig failing on CentOS 7.2
I just upgraded a machine to CentOS 7.2 and got the following error:
```
2016/01/13-09:13:22 -----------------------------------------------------------
2016/01/13-09:13:22 [ERROR] Trying to add details of unit netconsole.service but no entry in cache after adding all units and unitfiles. Ignoring this unit.
2016/01/13-09:13:25 [WARN] Found current unit netconsole.service via Chkconfig but is not in Unit. (This is unexpected, please notify the developers)
2016/01/13-09:13:48 [INFO] configure on component chkconfig executed, 1 errors, 1 warnings
```

I don't know what is `netconsole` but I am acting as requested: i'm contacting the developpers!

### PR DESCRIPTION
**Pull request by stdweird**
Fixes #677 
Based on #615

### CODE REVIEW

**Comment by stdweird** [comment]
misses unittests, to be added soonish

**Comment by jouvin** [comment]
Successfully tested at LAL. I'm ready to merge it as soon as unit test have been aded.

**Comment by stdweird** [comment]
@jouvin unittest added, commit squashed

**Comment by jouvin** [comment]
This PR seems to be a superset of #615. I don't really like this! What I tested at LAL is the end result of #615 + this PR (I rebuild `mc-systemd` from your branch). I suggest merging #615 first, do you agree?

**Comment by stdweird** [comment]
@jouvin yes, #615 should be merged first. i didn't bother to check if the commit can be applied separately to master; but maintaining multiple branches of the same component is not that easy.

**Comment by jouvin** [comment]
Do you see any good reason to delay #615 merging?

**Comment by stdweird** [comment]
not at all, we are running #615 for a while now, and i think i addressed all @ned21 remarks

**Comment by jouvin** [comment]
@stdweird please could you rebase on master, I just merged #615.

**Pull request merged**
