### PR TITLE
Update all components to latest maven tools

### PR DESCRIPTION
**Pull request by jrha**
From 1.42 to 1.44.

### CODE REVIEW

**Comment by jrha** [comment]
Passes tests :grinning:, any reasons not to do this?

**Comment by stdweird** [comment]
@jrha our unittests have more unittests then most of the components :smile: 
NEGTPIRT (not even going to pretend i reviewed this)

**Comment by jrha** [comment]
YCJIA - You Can't Just Invent Acronyms

**Comment by stdweird** [comment]
@jrha move to 1.44 and retest?

**Comment by jrha** [comment]
Done, tests passed :grinning:

**Pull request merged**
