### PR TITLE
ncm-network: support EL7 generic eno devices

### PR DESCRIPTION
**Pull request by stdweird**

### CODE REVIEW

**Comment by stdweird** [comment]
This is rebased on #461 (becuase that PR cleans up quite some code)

**Comment by ned21** [comment]
Code looks OK but something odd happened during the rebase as it pulled in a bunch of commits that are not related to ncm-network.

**Comment by stdweird** [comment]
@ned21 can you review #461? (this PR is only about the last commit)

**Comment by jrha** [comment]
@stdweird you can probably rebase this again now that #461 is merged.

**Comment by stdweird** [comment]
@jrha rebased

**Comment by jrha** [comment]
Well that's much simpler :smile:

**Pull request merged**
