### PR TITLE
ncm-metaconfig: service logstash add support for filter kv

### PR DESCRIPTION
**Pull request by stdweird**
Add support for the `bytes2human` and `kv` filters.

### CODE REVIEW

**Comment by itkovian** [comment]
It looks ok to me. But I am no expert.

**Comment by jrha** [comment]
Where does the `bytes2human` filter come from? It's not in upstream logstash AFAIK.

**Comment by stdweird** [comment]
we package it as part of our patterns (https://github.com/hpcugent/logstash-patterns/blob/master/logstash/filters/bytes2human.rb), someone opened an issue for it https://github.com/elastic/logstash/issues/3515

**Comment by stdweird** [comment]
and to be clear: this PR does not make it mandatory or anything like that

**Pull request merged**
