### PR TITLE
ncm-*: Update build tools to version 1.51

### PR DESCRIPTION
**Pull request by jrha**

### CODE REVIEW

**Comment by jrha** [comment]
:see_no_evil:

**Comment by stdweird** [comment]
i propose to do to move to the tqu unittest component per component, incl pan template cleanup. i'll make an example PR for a single component; but we should avoid fixing components that have open PRs.

**Comment by stdweird** [comment]
proposal to cleanup in https://github.com/quattor/quattor.github.com/pull/199

**Comment by stdweird** [comment]
https://github.com/quattor/configuration-modules-core/pull/1031 is an example of such cleanup. should be more or less in line with the post

**Comment by stdweird** [comment]
@jrha crap, the panlinter doesn't like maven templates.

**Comment by jrha** [comment]
Superseded by 1.52.

**Pull request closed without merging**
