### PR TITLE
ncm-accounts: switch to 00-tqu and code cleanup

### PR DESCRIPTION
**Pull request by stdweird**

### CODE REVIEW

**Comment by stdweird** [comment]
best viewed without whitespace changes https://github.com/quattor/configuration-modules-core/pull/1031/files?w=1

**Comment by stdweird** [comment]
@jrha crap, the panlinter doesn't like maven templates.

**Comment by stdweird** [comment]
this is the generated `config.pan`
```pan
#
# Software subject to following license(s):
#   Apache 2 License (http://www.opensource.org/licenses/apache2.0)
#   Copyright (c) Responsible Organization
#

#
# Current developer(s):
#   Luis Fernando Muñoz Mejías <Luis.Munoz@UGent.be>
#



unique template components/accounts/config;

include 'components/accounts/schema';

bind '/software/components/accounts' = accounts_component;

'/software/packages' = pkg_repl('ncm-accounts', '16.12.1-SNAPSHOT20170210112702', 'noarch');

include if_exists('components/accounts/site-config.pan');

prefix '/software/components/accounts';
'active' ?= true;
'dispatch' ?= true;
'version' ?= '16.12.1';
'dependencies/pre' ?= list('spma');

include 'components/accounts/functions';

# Include system users and groups which shouldn't be removed
# by default.  The machine configuration can still modify or
# remove them manually.
include 'components/accounts/sysgroups';
include 'components/accounts/sysusers';
```

**Comment by jrha** [comment]
Ignore it and I'll add an option to allow templates?

**Comment by stdweird** [comment]
i'm a bit surprised that the panlinter is ran on the src templates, not the ones that are created by parsing.

**Comment by jrha** [comment]
It's run on anything that looks like a pan template that was modified in the PR

**Comment by jrha** [comment]
I've opened a PR for panlint, once it is merged add `--allow_mvn_templates` to `travis-build`

**Comment by stdweird** [comment]
@jrha travis is 🍏 🥗 📗 ! thx

**Pull request merged**
