### PR TITLE
ncm-systemd: always use systemctl show data for non-listed unit

### LINKED ISSUE #686: ncm-systemd: error caused by legacy service off
On VMs with image managed by Quattor, we disable (set to off) `cdp-listend` and `ncm-cdispd` services. I saw that this was causing errors when running `ncm-systemd` (EL7, in the example below `ncm-cdispd` is off):
```
[INFO] running component: chkconfig
---------------------------------------------------------
updated /var/run/quattor-components/chkconfig
[WARN] Found current unit cdp-listend.service via Chkconfig but is not in Unit. (This is unexpected, please notify the developers)
[ERROR] get_unit_show: no alias for unit cdp-listend.service defined. (Forgot to update cache?)
[ERROR] get_unit_show: no alias for unit cdp-listend.service defined. (Forgot to update cache?)
[ERROR] is_active no ActiveState for unit cdp-listend.service found.
[ERROR] systemctl_command_units /usr/bin/systemctl start -- fetch-crl-boot.service returned ec 256 and output Job for fetch-crl-boot.service failed because the control process exited with error code. See "systemctl status fetch-crl-boot.service" and "journalctl -xe" for details.

[INFO] configure on component chkconfig executed, 4 errors, 1 warnings
updated /var/run/quattor-components/chkconfig
```

Doing a `chkconfig --level 345 xxx on` is enough to fix the problem. IMO, this is an unexpected behaviour...

### PR DESCRIPTION
**Pull request by stdweird**
Fixes #686

### CODE REVIEW

**Comment by stdweird** [comment]
@jouvin can you try this patch?

**Comment by jouvin** [comment]
On my development machines, unit tests are failing:
```
No root path(s) specified
 at src/test/perl/unitfile.t line 151

#   Failed test '_directory_exists false on missing directory'
#   at src/test/perl/unitfile.t line 152.

#   Failed test '_exists false on missing directory'
#   at src/test/perl/unitfile.t line 154.
# 
# [Service]
# CPUAffinity=
# CPUAffinity=0 1 2 12 13 14 6 7 8 18 19 20
# 
# 
# [Unit]
# AssertPathExists=
# AssertPathExists=/path/1
# AssertPathExists=/path/2
# 
# Looks like you failed 2 tests of 82.
src/test/perl/unitfile.t ..................... 
```

**Comment by jouvin** [comment]
Otherwise tested successfully on a machine exhibiting the problem (no `ncm-chkconfig` error reported).

**Comment by jouvin** [comment]
BTW, it was the same for 15.8.0 but we never tried to deploy it here...

**Comment by stdweird** [comment]
odd. did you run `mvn clean` first? (i'm not sure the tests cleanup any created dirs/files)

**Comment by stdweird** [comment]
added unittest for this issue

**Comment by jouvin** [comment]
You are right, tests are ok with `clean` (that I always forget!).

**Pull request merged**
