### PR TITLE
ncm-mysql: set initOnce to true by default

### PR DESCRIPTION
**Pull request by wdpypere**
I ran into a (luckily test) server dropping and recreating the database everytime ncm-mysql ran because this is set to false.

I do believe the use case of recreating every time is less likely than setting it up once. So setting it to true is more "what somebody would expect" IMHO.

### CODE REVIEW

**Comment by wdpypere** [comment]
there is one line which has a panlint error which I won't be able to fix.

**Comment by ned21** [comment]
Code looks fine but can you make the commit messages more descriptive please? They should mention the component name in the title, so e.g.

```
ncm-mysql: set initOnce to true by default

In the default configuration the databases would be dropped and recreated each time the
component ran which could lead to dataloss. This use case seems less likely than the
use case where initOnce=true.
```
```
ncm-mysql: modify PAN to pass panlint
```

**Comment by wdpypere** [comment]
@ned21 commit messages updated

**Comment by ned21** [comment]
Thanks for the update. jenkins seems to be down so I can't see why this failed but otherwise this LGTM

**Comment by ned21** [comment]
retest this please

**Comment by jrha** [comment]
@wdpypere LGTM, jenkins0 isn't currently visible outside UGent, so could you have a look and see what is causing the tests to fail?

**Comment by stdweird** [comment]
retest this please
@jrha test results are gone. i'll rerun them

**Comment by wdpypere** [comment]
@jrha tests pass again.

**Comment by jrha** [comment]
Cool. Could you squash c9f81b6e12d7c805c9b0677955367311fb50ed8a, aa81b1b93549df0de8a575ecc2af225cc80543c2 and a487daa82e0da1853c9190a561249655e4d5147a into one commit please?

**Comment by wdpypere** [comment]
@jrha Done

**Pull request merged**
