### PR TITLE
ncm-opennebula: Configure Opennebula services on demand

### LINKED ISSUE #570: ncm-opennebula: Configure different OpenNebula services only if its required
At this moment the component tries to configure every one service. We should configure only the services that are required (checking the conf tree) as example:
-oned
-datastores
-sunstone
..

### PR DESCRIPTION
**Pull request by alvarosimon**
OpenNebula services are configured on demand. Most of the schema values are optional now:

 * Fix #570 : Configure different OpenNebula services only if its required

### CODE REVIEW

**Comment by stdweird** [comment]
LGTM

**Comment by stdweird** [comment]
@alvarosimon can you rebase on latest master? (do not press the 'update branch' button ever :smile: )

**Comment by alvarosimon** [comment]
done!

**Comment by jrha** [comment]
@apdibbo, you may want to have a look at this one.

**Pull request merged**
