### PR TITLE
ncm-nmstate: remove confusing warning in IPv6 configuration

### LINKED ISSUE #1732: ncm-nmstate 24.10.0-rc5: remove warning about IPv6 configuration
`ncm-nmstate` [24.10.0-rc5](https://github.com/quattor/release/issues/367) implements IPv6 configuration but has a confusing warnining saying `ipv6 addr still under development` at https://github.com/quattor/configuration-modules-core/blob/a2c2145d16d1b11286d03e22c5188d98c7d6cf24/ncm-network/src/main/perl/nmstate.pm#L505

This warning brings no useful information. It should be removed or replaced by something specifying what is missing before 24.10.0 final release.

### PR DESCRIPTION
**Pull request by jouvin**
Fixes #1732

### CODE REVIEW

**Comment by jrha** [comment]
Thanks, IIRC all that is missing now is additional route support for IPv6.

**Comment by jouvin** [comment]
Do you think it is worth keeping an information message (rather than a warning) about it? AFAIC, I'd say no but it may be useful to open an issue to keep track of this...

**Comment by jrha** [comment]
No, but a definitely an issue, maybe also a schema warning…

**Review by jrha — APPROVED** [review]

**Comment by jrha** [comment]
NVM, it appears it was fixed.

**Comment by jrha** [comment]
#1734.

**Pull request merged**
