### PR TITLE
ncm-metaconfig: switch to CAF::ServiceActions

### PR DESCRIPTION
**Pull request by stdweird**
Requires https://github.com/quattor/CAF/pull/267

### CODE REVIEW

**Comment by jrha** [comment]
@hpcugentbot test this please

**Comment by jrha** [comment]
@stdweird are you able to rebase and take a look at what Jenkins is complaining about (I can't access the web-page)?

**Comment by jrha** [comment]
rebased

**Comment by ned21** [comment]
I can now see the failure in GH, but no idea what it means!

**Comment by stdweird** [comment]
test this please

**Comment by stdweird** [comment]
progress, i now have the same error on my laptop

**Comment by stdweird** [comment]
test this please

**Comment by stdweird** [comment]
@jrha also green now

**Comment by jrha** [comment]
:green_heart: !

**Comment by jrha** [comment]
At first glance LGTM, other than typo in commit message (ncm-metacon**if**g)

**Comment by stdweird** [comment]
@jrha typo fixed

**Review by ned21 — APPROVED** [review]

**Pull request merged**
