### PR TITLE
ncm-spma: Fix concatenation bug in yum repository headers

### PR DESCRIPTION
**Pull request by jrha**
The current code accidentally hides part of the header in unused arguments resulting in a header like:
```cfg
# File generated by 
# Basic Yum repository file. See the man pages for
# NCM::Component::spma and yum.conf
# for more details.
```

Instead of:
```cfg
# File generated by NCM::Component::spma::yum. Do not edit
# Basic Yum repository file. See the man pages for
# NCM::Component::spma and yum.conf
# for more details.
```

### CODE REVIEW

**Comment by stdweird** [comment]
unittest?

**Comment by jrha** [comment]
For a comment line? Is it essential functionality?

**Comment by stdweird** [comment]
well, you seemed to care 😄 . i can merge or approve this as is, no worries

**Comment by jrha** [comment]
I noticed it and it bugged me, didn't break anything though.

**Comment by jrha** [comment]
@stdweird IMHO this can be merged as is.

**Pull request merged**
