### PR TITLE
ncm-metaconfig: ganesha: fix Access_Type type

### PR DESCRIPTION
**Pull request by kwaegema**
Access_Type should be a string

### CODE REVIEW

**Comment by jrha** [comment]
Bug fix?

**Comment by stdweird** [comment]
@kwaegema add `ncm-metaconfig: ganesha` to the title
@jrha unittests fail on EL5 due to this (more recent TT allow all list vmethods on strings)

**Comment by jrha** [comment]
This change causes tests to fail on SL5, or fixes tests that were failing?

**Comment by stdweird** [comment]
this fixes failing unittests on EL5

**Pull request merged**
