### PR TITLE
ncm-altlogrotate: typo in ifempty key, fixes issue #1326

### PR DESCRIPTION
**Pull request by aka7**
fixes issue #1326
ifempty key does not currently take effect. regardless of if set to true or false.
this is due to typo in ifempty, in file src/main/perl/altlogrotate.pm, ( see line 27 and 46 )

Tested locally by correcting the typo,
when set to false, config has 'noifempty'.
when set to true, config has 'ifempty'.

### CODE REVIEW

**Comment by stdweird** [comment]
@aka7 thanks for noticing/fixing. i expect the unittests to fail because the test config hash ifempty configuration (eg https://github.com/quattor/configuration-modules-core/blob/master/ncm-altlogrotate/src/test/resources/simple.pan#L12), but no ifempty in the output eg https://github.com/quattor/configuration-modules-core/blob/master/ncm-altlogrotate/src/test/perl/simple.t#L20
so you will have to address this

**Comment by aka7** [comment]
> @aka7 thanks for noticing/fixing. i expect the unittests to fail because the test config hash ifempty configuration (eg https://github.com/quattor/configuration-modules-core/blob/master/ncm-altlogrotate/src/test/resources/simple.pan#L12), but no ifempty in the output eg https://github.com/quattor/configuration-modules-core/blob/master/ncm-altlogrotate/src/test/perl/simple.t#L20
> so you will have to address this

ah sorry, hope this will pass.

**Comment by stdweird** [comment]
@aka7 so it fails (which is good since you fixed a bug): you will have to adjust the expected output for the new ifempty/notifempty values

https://jenkins0.ugent.be/job/NCM_Components-pull_requests/2680/org.quattor.cfg.module$altlogrotate/console
```
#   Failed test 'correct global config entry'
#   at src/test/perl/simple.t line 52.
#          got: '
# #
# # Generated by ncm-altlogrotate.
# #
# include some_file
# something {
# notifempty
# tabooext + a,b
# }
# '
#     expected: '
# #
# # Generated by ncm-altlogrotate.
# #
# include some_file
# something {
# tabooext + a,b
# }
# '

#   Failed test 'correct test1 config entry'
#   at src/test/perl/simple.t line 56.
#          got: '
# #
# # Generated by ncm-altlogrotate.
# #
# a/b/c/*-2???-??-??.log {
# compress
# ifempty
# missingok
# rotate 1
# daily
# create 0751 someuser agroup
# mailfirst
# nomail
# tabooext a,b
# lastaction
# 
# /run/this
# 
# endscript
# }
# '
#     expected: '
# #
# # Generated by ncm-altlogrotate.
# #
# a/b/c/*-2???-??-??.log {
# compress
# missingok
# rotate 1
# daily
# create 0751 someuser agroup
# mailfirst
# nomail
# tabooext a,b
# lastaction
# 
# /run/this
# 
# endscript
# }
# '
```

**Comment by aka7** [comment]
Hi @stdweird 
I'll take a look tomorrow.  I haven't set up my local environment.  wasn't expecting run tests :) I probably should do this first.

thanks.

**Comment by aka7** [comment]
Hi @stdweird 
I think I have now corrected the tests, but looks like the jobs is not running again, could it because I did git commit --amend ? could you please check.

I'm straggling to setup a local environment to run the tests, perhaps you can point me to the right documentation on the best to setup dev environment where I can run the tests locally first?

regards

**Comment by ned21** [comment]
@hpcugentbot test this please

**Comment by jrha** [comment]
@aka7 @stdweird — seems like the tests ran and passed, all happy now?

**Pull request merged**
