### PR TITLE
ncm-download: switch to CAF::Download::LWP

### PR DESCRIPTION
**Pull request by stdweird**
Replaces #925 
Requires https://github.com/quattor/CAF/pull/203

### CODE REVIEW

**Comment by stdweird** [comment]
needs more testing

**Comment by stdweird** [comment]
retest this please

**Comment by ned21** [comment]
@ajf8 Since you've done lots of work on download recently, can you take a look at this one please?

**Comment by jrha** [comment]
Merged, but would still be good if @ajf8 could take a look.

**Pull request merged**
