### PR TITLE
ncm-useraccess: spring cleanup

### PR DESCRIPTION
**Pull request by stdweird**
Backwards incompatible: sets both spma and accounts as predependency

### CODE REVIEW

**Comment by stdweird** [comment]
@ned21 @jrha same remarks as with #1247

**Comment by ned21** [comment]
Not familiar with this component but code looks OK. Would be better for someone who actually uses it to check it more closely!

**Comment by jrha** [comment]
Hmm, not an issue with this change per-se, but do all of the test profiles actually get compiled? One of the files that you renamed that has been flagged by Panlint looks suspiciously like it should not compile, see [lines 20-22 of testrolesimple.pan](https://github.com/stdweird/configuration-modules-core/blob/cb92254c2b1531882d4b3a7d80469ece4c8482b5/ncm-useraccess/src/test/resources/testrolesimple.pan#L20-L22).

**Comment by stdweird** [comment]
@jrha only files used in perl unittests get used. i'll fix this

**Comment by jrha** [comment]
If they're not used and don't work just delete them?

**Pull request merged**
