### PR TITLE
ncm-metaconfig: dellnetworking: support disabling ipv6

### PR DESCRIPTION
**Pull request by stdweird**

### CODE REVIEW

**Comment by stdweird** [comment]
jenkins test this please

**Review by jrha — APPROVED** [review]
Still LGTM

**Comment by jrha** [comment]
Actually hang on, this says ncm-network, but this is all for metaconfig?

**Comment by stdweird** [comment]
@jrha oopsie. i'll change it

**Comment by stdweird** [comment]
@jrha fixed

**Review by jrha — APPROVED** [review]
Looks even better to me :grin:

**Pull request merged**
