### PR TITLE
ncm-syslog: escape certain special regexp characters

### PR DESCRIPTION
**Pull request by stdweird**
Fixes issue reported in https://github.com/quattor/release/issues/301#issuecomment-320619630

### CODE REVIEW

**Comment by stdweird** [comment]
@jrha can you give this a try?

**Comment by jrha** [comment]
Works correctly on SL6, inserts an extra blank line after `$IncludeConfig` compared to 17.3.0, which might cause spurious service restarts.

**Comment by jrha** [comment]
Works correctly on SL7 too, same extra blank line (largely harmless).

**Comment by stdweird** [comment]
@jrha there's a double newline at the end?

**Comment by jrha** [comment]
When I upgrade and downgrade number of newlines between the header and rules changes, but I don't think it matters.

For example on SL7:

```diff
--- rsyslog.conf	(ncm-syslog-17.3.0)
+++ rsyslog.conf	(ncm-syslog-17.7.0-rc3_SNAPSHOT20170808092410)
@@ -5,12 +5,24 @@
 $IncludeConfig /etc/rsyslog.d/*.conf     # ncm-syslog
 $OmitLocalLogging on                     # ncm-syslog
 $IMJournalStateFile imjournal.state      # ncm-syslog
+
+
+
+
+
+
+
+
+
+
+
+
 *.info;mail.none;authpriv.none;cron.none	/var/log/messages
 authpriv.*	/var/log/secure
 mail.*	/var/log/maillog
 cron.*	/var/log/cron
 *.emerg	:omusrmsg:*
-uucp,news.crit	/var/log/spooler
+uucp,news.crit;uucp.crit	/var/log/spooler
 local7.*	/var/log/boot.log
```

Hmm, I hadn't spotted that the spooler line changes either...

**Comment by stdweird** [comment]
@jrha can you paste `ccm /software/components/syslog`?

**Comment by jrha** [comment]
Sure...
<details>

```
# ccm /software/components/syslog
+-/software/components/syslog
  $ active : true
  +-config
    +-0
      $ action : '/var/log/messages'
      +-selector
        +-0
          $ facility : '*'
          $ priority : 'info'
        +-1
          $ facility : 'mail'
          $ priority : 'none'
        +-2
          $ facility : 'authpriv'
          $ priority : 'none'
        +-3
          $ facility : 'cron'
          $ priority : 'none'
    +-1
      $ action : '/var/log/secure'
      +-selector
        +-0
          $ facility : 'authpriv'
          $ priority : '*'
    +-2
      $ action : '/var/log/maillog'
      +-selector
        +-0
          $ facility : 'mail'
          $ priority : '*'
    +-3
      $ action : '/var/log/cron'
      +-selector
        +-0
          $ facility : 'cron'
          $ priority : '*'
    +-4
      $ action : ':omusrmsg:*'
      +-selector
        +-0
          $ facility : '*'
          $ priority : 'emerg'
    +-5
      $ action : '/var/log/spooler'
      +-selector
        +-0
          $ facility : 'uucp,news'
          $ priority : 'crit'
    +-6
      $ action : '/var/log/boot.log'
      +-selector
        +-0
          $ facility : 'local7'
          $ priority : '*'
    +-7
      $ action : '@host1.example.org'
      +-selector
        +-0
          $ facility : '*'
          $ priority : '*'
    +-8
      $ action : '@host2.example.org'
      +-selector
        +-0
          $ facility : '*'
          $ priority : '*'
  $ daemontype : 'rsyslog'
  +-dependencies
    +-pre
      $ 0 : 'spma'
  +-directives
    $ 0 : '$MaxMessageSize 4096'
    $ 1 : '$ModLoad imuxsock'
    $ 2 : '$ModLoad imjournal'
    $ 3 : '$WorkDirectory /var/lib/rsyslog'
    $ 4 : '$IncludeConfig /etc/rsyslog.d/*.conf'
    $ 5 : '$OmitLocalLogging on'
    $ 6 : '$IMJournalStateFile imjournal.state'
  $ dispatch : true
  $ fullcontrol : false
  $ syslogdoptions : ''
  $ version : '17.7.0'
```

</details>

**Comment by stdweird** [comment]
@jrha does the number of newlines increase with each ncm-metaconfig run?

**Comment by jrha** [comment]
Yes, an extra line is added each time.

**Comment by stdweird** [comment]
ok, the spooler line is defintely a bug. we use `fullcontrol = true`, so i hadn't seen this before.

**Comment by ned21** [comment]
👍 for ```<details>``` in a comment - not seen that before.

**Pull request merged**
