### PR TITLE
ncm-aiiserver: do not add (empty) attributes for unused CCM properties

### LINKED ISSUE #970: aii-server 16.10.0-rc3: keyword without values added
In 16.10.0 release candidates (including RC3), ncm-aiiserver produces a `aii-shellfe.conf` file with keywords without a value, causing aii-shellfe to fail. This includes: 
```
ca_dir =
ca_file =
cert_file =
key_file =
``` 

This is a showstopper for release [16.10.0](https://github.com/quattor/release/issues/269).

### PR DESCRIPTION
**Pull request by stdweird**
Fixes #970

### CODE REVIEW

**Comment by stdweird** [comment]
@jouvin this should work

**Comment by jouvin** [comment]
Thanks. I'm testing it...

**Comment by jouvin** [comment]
Thanks for the quick fix. I confirm that it works.

**Comment by jrha** [comment]
Awesome.

**Comment by jrha** [comment]
Tests just failed on the OpenNebula component, I suspect it is the same error as I was seeing with the Perl library version.

**Pull request merged**
