### PR TITLE
Remove config-xml from components

### PR DESCRIPTION
**Pull request by jrha**
We removed support for shipping the components in the profile from ncm-ncd in quattor/ncm-ncd#36,
so these templates have been useless since then.

This is also covered by #545.

### CODE REVIEW

**Comment by stdweird** [comment]
retest this please

**Comment by stdweird** [comment]
LGTM
@ned21 @jouvin any objections?

**Comment by ned21** [comment]
:ship: :fireworks: :sunglasses:

**Comment by stdweird** [comment]
:confused: 
i'll ask github support for a an appropriate emoji for `:you_can_always_revert_the_merge_if_i_misunderstood_the_series_of_emoji:`

**Comment by jrha** [comment]
:see_no_evil:

**Pull request merged**
