### PR TITLE
ncm-metaconfig: pass element instance to CCM::TextRender

### PR DESCRIPTION
**Pull request by stdweird**
Allows generation of schema compliant YAML and JSON, and prepares for more Element features as part TT environment

### CODE REVIEW

**Comment by stdweird** [comment]
requires https://github.com/quattor/CCM/pull/51

**Comment by stdweird** [comment]
@jrha besides the CCM PR, this requires new build-tools, that will require the new CCM to perform the tests in a way that metaconfig will function (the current unittests will use `CAF::TextRender`, not `CCM::TextRender`)
but that change in the build-scripts will break all unittests when CCM is not updated.

i propose to merge this PR and CCM PR, then make a rc1, and release new build tools for rc2. that way, people can use the CCM rc1 to test.

**Comment by jrha** [comment]
@stdweird are you saying that this should be merged even though it is failing tests?

**Comment by stdweird** [comment]
@jrha no, certainly not with failing tests. but we need new build-tools first. the PRs there are merged, but is 1.44 out?

**Comment by jrha** [comment]
Oh I see, sorry. I missed the need for new maven tools, I'll get on that after lunch.

**Comment by jrha** [comment]
Ok, 1.44 is released, it might take a while to show up on the Nexus though.

**Comment by jrha** [comment]
1.44 is up :grin:

**Comment by stdweird** [comment]
retest this please

**Comment by stdweird** [comment]
@jrha i verified that the tests use 1.44 and all things are still fine

**Comment by jrha** [comment]
Cool, I'll merge this when RC1 has finished baking.

**Pull request merged**
