### PR TITLE
ncm-metaconfig: add missing kafka options

### PR DESCRIPTION
**Pull request by wdpypere**

### CODE REVIEW

**Comment by wdpypere** [comment]
the should be `int.int` as a string. where it should match an actual kafka version. Do you have suggestions on how to improve the schema?

**Comment by jrha** [comment]
How about…
```pan
string with match(SELF, '^\d+\.\d+$');
```

**Comment by wdpypere** [comment]
thanks @jrha , fixed.

**Review by jrha — APPROVED** [review]
LGTM

**Pull request merged**
