### PR TITLE
Merge 19.12.0 release branch

### PR DESCRIPTION
**Pull request by ned21**
Update pom.xml and other files to match what was used to release 19.12.

### CODE REVIEW

**Comment by ned21** [comment]
I see there's an 18.12 branch too, should that also be merged first or deleted?

**Comment by stdweird** [comment]
jenkins test this please

**Comment by stdweird** [comment]
jenkins test this please

**Review by jrha — APPROVED** [review]
I guess this is a good idea, I really would like to get to the point where we don't have to disable `ncm-openstack` though.

**Pull request merged**
