### PR TITLE
ncm-metaconfig: rsyslog: Move common parts of schema to a common template

### PR DESCRIPTION
**Pull request by jrha**
Cleaner and allows for simpler testing when copied to core template library.

### CODE REVIEW

**Comment by jrha** [comment]
@stdweird any comments on wisdom/naming?

**Comment by stdweird** [comment]
@jrha not sure what you are asking...

**Comment by jrha** [comment]
Just whether you thought "common" is the right name.

**Comment by stdweird** [comment]
@jrha sure, why not?

**Pull request merged**
