### PR TITLE
ncm-openstack: add Magnum orchestration service

### PR DESCRIPTION
**Pull request by alvarosimon**
**NOTE:** This PR requires  #1393 , it should be reviewed/merged first. This PR also includes Barbican service.

 * Fix: #1397

### CODE REVIEW

**Comment by alvarosimon** [comment]
I will include Barbican service also into this PR

**Comment by apdibbo** [comment]
This one also looks good and I very much look forwards to putting this into use

**Comment by jrha** [comment]
@alvarosimon this will need rebasing on master now that the PRs it was based on have been merged.

How WIP is this still?

**Comment by alvarosimon** [comment]
@jrha @apdibbo , ah sorry I forgot to remove the WIP flag.. This pr is ready, we are already using it in our clusters.

**Pull request merged**
