### PR TITLE
ncm-metaconfig: haproxy - add mode option for frontend and backend and ACLs

### PR DESCRIPTION
**Pull request by wdpypere**
the schema (and TT code) only allows mode on general settings. It is also possible to set is specifically on frontend and backends. This PR enables that.

### CODE REVIEW

**Comment by ned21** [comment]
🎉  the GitHub action is working nicely! Only downside is that it produces 44k lines of output. 😢 Finding the error doesn't help as lots of tests produce "errors" as an expected result, so you can look for "not ok" -- looks like these errors are from this patch?

not ok 145 - Found at least one match (total 0 matches) for test idx 53 (pattern (?^:(?m:^\s{4}http-request\sredirect\sscheme\shttps\sunless\s\{ssl_fc\s\}$)))
26111
not ok 146 - Order ok for test idx 53 (pattern (?^:(?m:^\s{4}http-request\sredirect\sscheme\shttps\sunless\s\{ssl_fc\s\}$))) (lastpos 1600 before -1)

**Comment by wdpypere** [comment]
@ned21 thank you for spotting that one for me. :smile:

**Comment by ned21** [comment]
@wdpypere Can you rebar and squash e5ab6a4 into c85898a to keep the commit history a bit easier to follow please?

**Comment by wdpypere** [comment]
@ned21 done

**Review by jrha — APPROVED** [review]
LGTM

**Pull request merged**
