### PR TITLE
ncm-spma: support yum plugin configuration (including default versionlock and fastestmirror)

### LINKED ISSUE #534: ncm-spma: adding plugin support
currently, yum-based spma relies on the `versionlock` yum plugin; and on EL7, the `fastestmirror` plugin is also in use by default and can cause unwanted behaviour when running spma (see also #525).
none of these are currenlty controlled/managed by quattor.

i propose to add support for both in ncm-spma, but i'm struggling with the default behaviour. 
i.e. what does ncm-spma do when nothing is configured wrt plugins.

i would create the following configs by default: 
for versionlock
```
[main]
enabled=1
locklist = /etc/yum/pluginconf.d/versionlock.list
```

and for fastestmirror (generating the configfile, not making it a dependency of spma as is the case with versionlock)
```
[main]
enabled=0
```

any thoughts?

### PR DESCRIPTION
**Pull request by stdweird**
Also includes some cleanup and TT unittests
Fixes #534 #525

By default (i.e. unless the plugins are explicitly configured), this code will enable the versionlocklist plugin with config 
```
[main]
enabled=1
locklist=/etc/yum/pluginconf.d/versionlock.list
```
and disable the fastestmirror plugin with config
```
[main]
enabled=0
```

### CODE REVIEW

**Comment by stdweird** [comment]
tests will fail until we can use https://github.com/quattor/maven-tools/pull/56

**Comment by ned21** [comment]
Code looks OK to me.

**Comment by stdweird** [comment]
@ned21 are you also ok with the default behaviour? (i updated the description)

**Comment by ned21** [comment]
What you propose looks sensible, yes.

**Comment by stdweird** [comment]
@ned21 test run now with new buildtools

**Pull request merged**
