### PR TITLE
ncm-network: no error wrt missing (IPv4) ip and netmask in a pure IPv6 config

### LINKED ISSUE #1296: ncm-network: Returns an error when an interface is configured as IPv6 only
Hi,

When you want to create a interface w/o IPv4 [1], the component return a ERROR (but interface is configure correctly) w/ the output [2]
[1]
```
# Configure IPv6 interface on a VLAN dedicated to IPv6
prefix '/system/network/interfaces';
"vlan1901/onboot"       = "on";
"vlan1901/bootproto"    = "static";
"vlan1901/physdev"      = 'eth0';
"vlan1901/device"       = "eth0.1901";
"vlan1901/ipv6_autoconf" = false;
"vlan1901/ipv6addr"     = "2001:660:3024:100:134:158:73:243/64";
prefix '/system/network';
'ipv6/enabled' = true;
'ipv6/default_gateway' = "2001:660:3024:100::2";
```
[2]
```
2018/06/26-09:32:02 [VERB] [ERROR] Using static bootproto and no ipaddress configured for vlan1901
2018/06/26-09:32:02 [VERB] [ERROR] Using static bootproto and no netmask configured for vlan1901
```

### PR DESCRIPTION
**Pull request by stdweird**
Fixes #1296

### CODE REVIEW

**Comment by stdweird** [comment]
@jouvin completely untested (both pure ipv4 or otherwise)
@jrha i'll let you change the milestone :smile:

**Comment by jrha** [comment]
Thanks

**Comment by jouvin** [comment]
Tested on a machine with a VLAN configured only with an IPv6 address and it works perfectly. I let you and @jrha decide if it is still time to have it in 18.6.0...

**Comment by jrha** [comment]
Nope, definitely not, no time to test this and I want to get final out today.

**Pull request merged**
