### PR TITLE
ncm-metaconfig generic templates

### PR DESCRIPTION
**Pull request by stdweird**
support writing simple string literal and multine text with metaconfig
Requires #1387

### CODE REVIEW

**Comment by ned21** [comment]
I am guessing this is intended as as replacement for ncm-filecopy? Makes sense, perhaps mention that in the commit log. Also we need to update the tutorial? 

Any idea what's wrong with Jenkins?

**Comment by stdweird** [comment]
jenkins test this please

**Comment by stdweird** [comment]
test this please

**Comment by stdweird** [comment]
test this please

**Comment by stdweird** [comment]
test this please

**Pull request merged**
